repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--all", "--", "--check"]
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        args: ["--workspace", "--all-targets"]
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args: ["--workspace", "--all-targets", "--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
      - id: docs
        name: docs
        description: Build documentation
        entry: cargo
        args: ["doc", "--all-features", "--no-deps"]
        language: system
        types: [rust]
        pass_filenames: false
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: ["--fix", "--unsafe-fixes", "--config", "ruff.toml"]
      - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          [
            "--allow-subclassing-any",
            "--strict",
            "--ignore-missing-imports",
            "--scripts-are-modules",
            "--install-types",
            "--non-interactive",
          ]
