[workspace]
resolver = "2"
members = ["andino-core", "andino-dora"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0" # TODO(francocipollone): TBD
repository = "https://github.com/ekumenlabs/andino-rs"
