[project]
name = "andino-rs"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
]

[tool.uv.workspace]
members = [
  "dora_node_hub/dora_andino_mujoco_sim",
  "dora_node_hub/dora_gemini_diff_drive_navigation",
]
exclude = ['andino', 'andino_dora', 'andino_dora_sim',]
