[package]
name = "dora_teleop_keyboard"
description = "Teleoperation for a differential drive robot using keyboard input"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

eyre = { workspace = true }
dora-node-api = { workspace = true}
